### ISSUE TITLE
Can you please add a prop to disable autotranslate to English?

### ISSUE THREAD

**Issue by sanesanyo** [chengsokdara/use-whisper#1]
First of all, thank you for creating this awesome hook. The hook is automatically translating the transcribed text to English. Will it be possible to add a prop so that we can choose to set this translation to on or off? Additionally, instead of passing the server link, can we just also pass a function instead? The function then connects with the API directly & returns the response object.

Thank you once again.

**Comment by chengsokdara** [comment]
@sanesanyo thank you for these great ideas, I will add these features in the next release.

**Comment by sanesanyo** [comment]
Thanks. When will be the next release? Just to be clear, I do not want auto-transcribe to be set to false but the automatically translating the transcribed text to English to false i.e. the transcribed output should be in the original language. As of now, it is English. It will be great if you could push this feature as soon as possible :). 

Cheers

**Comment by sanesanyo** [comment]
Hi, I think there has been a misunderstanding :(. I think setting autoTranscribe to true by default makes a lot of sense. But what I was asking for was that within the API call to Whisper API, setting "translate" to false, which would mean that original speech text will be returned back not the translated text to English, which is what is happening right now.

**Comment by ringge** [comment]
same question, how to disable auto translate to English? 
Edit: Never mind, found the answer https://github.com/chengsokdara/use-whisper/issues/4
thanks
