### ISSUE TITLE
Invalid file format

### ISSUE THREAD

**Issue by leopoldpoldus** [chengsokdara/use-whisper#10]
When using your standard configuration: 

const App = () => {
  const {
    recording,
    speaking,
    transcribing,
    transcript,
    pauseRecording,
    startRecording,
    stopRecording,
  } = useWhisper({
    apiKey: import.meta.env.VITE_OPENAI_API_KEY, // YOUR_OPEN_AI_TOKEN
  })

  return (
    <div>
      <p>Recording: {recording}</p>
      <p>Speaking: {speaking}</p>
      <p>Transcribing: {transcribing}</p>
      <p>Transcribed Text: {transcript.text}</p>
      <button onClick={() => startRecording()}>Start</button>
      <button onClick={() => pauseRecording()}>Pause</button>
      <button onClick={() => stopRecording()}>Stop</button>
    </div>
  )
}

 Error: Invalid file format. Supported formats: ['m4a', 'mp3', 'webm', 'mp4', 'mpga', 'wav', 'mpeg']

**Comment by chengsokdara** [comment]
Hello @leopoldpoldus, can you tell me what device platform and browser you test this on?

This package tested on Mac + Chrome, I believe this might be other platform or browser combination that output unknown format.

**Comment by chengsokdara** [comment]
@leopoldpoldus I am thinking of using .wav to see if it output the same file on any platform and browser.
I will add this in the next version.
