### ISSUE TITLE
Storing transcript text in a variable problem

### ISSUE THREAD

**Issue by ThantHtetAung101** [chengsokdara/use-whisper#11]
I'm currently using your library in my project and everything work fine. But somehow, I can't store tanscript text as soon as the response get back from api. I could use setTimeout and store the textContext of DOM element output in a variable but it's not flexible and efficient. It would be better if I could store the transcript text right after getting the response.
This is how I'm currently using - 
`const data = useWhisper({
        apiKey: "<MY API KEY>"
    })
    const handleInput = async () => {
        await data.stopRecording();
        setTimeout(() => {
            let text = document.getElementById('myText').textContent
            console.log(text);
            handleAnswer(text)
        }, 500);
    }`

**Comment by chengsokdara** [comment]
Hello @ThantHtetAung101

This is because after onStopRecording it will process audio data and send to Whisper before it get the result, so catching transcribed text inside onStopRecording will not work.

If you want to save transcribed text, you should use useEffect instead.

```javascript
const [texts, setTexts] = useState([])
const { transcript } = useWhisper(yourConfig)

useEffect(() => {
  if (transcript.text) {
    setTexts([...texts, transcript.text])
  }
}, [transcript])
```
