### ISSUE TITLE
Safari support?

### ISSUE THREAD

**Issue by sgrove** [chengsokdara/use-whisper#13]
I think Safari may not support the current codec used, but I'm not sure if there's a way to detect what codecs a browser supports at runtime.

**Comment by chengsokdara** [comment]
@sgrove I just aware of it, currently I am testing wav format for cross-browser support, expect an update soon

**Comment by chengsokdara** [comment]
@sgrove I just release v0.2.0 that should work on Safari.

0.2.0 will record in lossless wav format and use lamejs to encode into mp3 that should work across all browsers.
