### ISSUE TITLE
Is it possible to capture the state if the user is currently speaking or not in the object that is returned by the hook?

### ISSUE THREAD

**Issue by sanesanyo** [chengsokdara/use-whisper#5]
I want to automatically start recording as soon as the browser detects that the user is speaking, thus if I can get that state in the return object, that will be really awesome.

Thanks a lot once again.

**Comment by sanesanyo** [comment]
Additionally, I also need some help with the server side implementation of Open AI API. I have spent last 2 hours trying to get it working but with little success. It is throwing errors like fs.readFileStream is not a function. Could you please share how you called the API on the server side?

**Comment by chengsokdara** [comment]
@sanesanyo I used to detect user is speaking and start recording but it does not work well, when the recorder start recording some word was cut out. So not recommend.

if you try to read file in Node.js use fs.createFileStream and assume u use official openai library

```javascript
const file = createReadStream('output.mp3')
const transcription = await openai.createTranscription(
  file,
  models.whisper,
  undefined,
  undefined,
  undefined,
  'en'
 )
```

**Comment by sanesanyo** [comment]
Thanks. The issue I am facing is that how to convert the base64 object to the file object on the server side. I also tried to send the file object such as new File([blob], "speech.mp3"....) and then on server side: const file = fs.createReadStream(fileObject) but that was also throwing errors such as fs.createReadStream does not exist. Do you know what would be the best way to implement this given you have already done this on the server side?

**Comment by chengsokdara** [comment]
@sanesanyo you need to save the file first before createReadStream.

```javascript
const base64data = audio.replace('data:audio/webm;codec=opus;base64,', '')
const audioData = Buffer.from(base64data, 'base64')
fs.writeFileSync('audio.mp3', audioData)
const file = fs.createReadStream('audio.mp3')
const transcription = await openai.createTranscription(file, 'whisper-1')
```

**Comment by sanesanyo** [comment]
Thanks, that helps. On other front, can you please also pass the whisperConfig to the onTranscribe callback as well? I need to pass the whisperConfig to the server side as well. Based on what I saw in your code, this should be rather a straightforward fix. Thank you once again.

**Comment by chengsokdara** [comment]
@sanesanyo since you use custom server, no need to pass whisperConfig if you use onTranscribe.

you can create your own whisperConfig inside onTranscribe callback directly.

**Comment by sanesanyo** [comment]
Right but my whisperConfig is dynamic which I would like to pass directly from the hook. The user can pick a different language and I only know about that only in the component where i am calling the hook and I am feeding this information into the whisperConfig. I would be extremely grateful if you could also pass the whisperConfig as the second argument to the onTranscribe callback or pass an object containing the blob and whisperConfig. Thanks.

**Comment by chengsokdara** [comment]
@sanesanyo still not think it is a good use case.
When you use onTranscribe it means you will handle server side on your end. So whisperConfig should not be use with onTranscribe at all.
whisperConfig is just an option you pass to actual Whisper API endpoint, so if you should handle it on your backend not with useWhisper.

**Comment by sanesanyo** [comment]
No problem, I understood. I have made my own custom hook where i am passing the config to the callback :). Thanks for your help.
